export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const COMPANY_LOGIN_SUCCESS = "COMPANY_LOGIN_SUCCESS"
export const COMPANY_LOGIN_ERROR = "COMPANY_LOGIN_ERROR"
